### ISSUE TITLE
`TypeError: program.prompt is not a function` when running `jira config`

### ISSUE THREAD

**Issue by rummik** [danshumaker/jira-cli#1]
- Using Node.js 10.15.3
- Jira CLI 1.1.0

Output from `jira config`:

```
Did not find config file from JIRA_CONFIG environment variable or /Users/rummik/.jira-cli/config.json.

Setting one up in /Users/rummik/.jira-cli/config.json

TypeError: program.prompt is not a function
    at Object.ask (/Users/rummik/.config/yarn/global/node_modules/jira-cli/lib/auth.js:48:25)
    at Object.setup (/Users/rummik/.config/yarn/global/node_modules/jira-cli/lib/auth.js:63:22)
    at Command.<anonymous> (/Users/rummik/.config/yarn/global/node_modules/jira-cli/bin/jira.js:297:24)
    at Command.listener (/Users/rummik/.config/yarn/global/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:189:13)
    at Command.parseArgs (/Users/rummik/.config/yarn/global/node_modules/commander/index.js:651:12)
    at Command.parse (/Users/rummik/.config/yarn/global/node_modules/commander/index.js:474:21)
    at /Users/rummik/.config/yarn/global/node_modules/jira-cli/bin/jira.js:373:13
    at Object.execCb (/Users/rummik/.config/yarn/global/node_modules/requirejs/bin/r.js:1941:33)
    at Module.check (/Users/rummik/.config/yarn/global/node_modules/requirejs/bin/r.js:1116:51)
```

**Comment by danshumaker** [comment]
Thanks for reporting this Rummik.  I've converted the tool to use enquirer instead of prompt.  But it looks like that program.prompt is an old one that needs to be converted.  It shouldn't take too long to fix.  I'll ping this thread asap when fixed.

**Comment by danshumaker** [comment]
@rummik Try again with version 1.5.1
