### ISSUE TITLE
jira new do not provide error message

### ISSUE THREAD

**Issue by mikhaili** [danshumaker/jira-cli#13]
i'm trying to run jira new and it fail on missing reporter but the error was not displayed

**Comment by danshumaker** [comment]
Hi @mikhaili , it seems to work for me
https://asciinema.org/a/gocLZDcSIVgXUW93ROFeHfVje

Have you authenticated yet?  I believe the initial default "reporter" is you (whatever user specified in .jira-cli/config.json).

**Comment by danshumaker** [comment]
https://github.com/danshumaker/jira-cli/issues/12

**Comment by danshumaker** [comment]
You can also try the verbose ( -v ) cli option. It should print out more info.  However, I havn't tested that much and I just updated the superagent lib and it puts errors in a different spot (object).

**Comment by mikhaili** [comment]
` { Error: cannot POST /jira/rest/api/2/issue (400)
       at Response.toError (/Users/mikhaili/.nvm/versions/node/v10.16.3/lib/node_modules/jira-cli/node_modules/superagent/lib/node/response.js:95:13)
       at ResponseBase._setStatusProperties (/Users/mikhaili/.nvm/versions/node/v10.16.3/lib/node_modules/jira-cli/node_modules/superagent/lib/response-base.js:123:16)
       at new Response (/Users/mikhaili/.nvm/versions/node/v10.16.3/lib/node_modules/jira-cli/node_modules/superagent/lib/node/response.js:41:8)
       at Request._emitResponse (/Users/mikhaili/.nvm/versions/node/v10.16.3/lib/node_modules/jira-cli/node_modules/superagent/lib/node/index.js:728:20)
       at /Users/mikhaili/.nvm/versions/node/v10.16.3/lib/node_modules/jira-cli/node_modules/superagent/lib/node/index.js:891:38
       at Stream.<anonymous> (/Users/mikhaili/.nvm/versions/node/v10.16.3/lib/node_modules/jira-cli/node_modules/superagent/lib/node/parsers/json.js:17:7)
       at Stream.emit (events.js:198:13)
       at Unzip.<anonymous> (/Users/mikhaili/.nvm/versions/node/v10.16.3/lib/node_modules/jira-cli/node_modules/superagent/lib/node/unzip.js:54:12)
       at Unzip.emit (events.js:203:15)
       at endReadableNT (_stream_readable.js:1145:12)
     status: 400,`

**Comment by mikhaili** [comment]
jira create work ok but have no description
jira new fail silently

**Comment by danshumaker** [comment]
@mikhaili  Try using the "-d" cli option on create  (see `jira create -h`)    That added a description for me.   Otherwise the default `jira create`  does not allow setting a description.

You have the latest version = 1.5.0 ?

**Comment by mikhaili** [comment]
yes latest with -d it work great just was wonder if it by design no description
