### ISSUE TITLE
Error when opening issues

### ISSUE THREAD

**Issue by mhogerheijde** [danshumaker/jira-cli#42]
When I run the command `jira open <ISSUE-ID>` I get the following error:

```
/home/matthias/.n/lib/node_modules/jira-cli/node_modules/openurl/openurl.js:39
                throw error;
                ^

Error: [260087:260087:1117/141321.958923:ERROR:chrome_content_client.cc(343)] Failed to locate and load the component updated flash plugin.

    at Socket.<anonymous> (/home/matthias/.n/lib/node_modules/jira-cli/node_modules/openurl/openurl.js:35:25)
    at Socket.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

I think the error about flash not being installed is from the Chromium-based browser I use, one could argue that its errors should not propagate to the CLI (unless the browser actually doesn't start?).

To compare, a tool like `xdg-open` does indeed itself exit with zero status, even though the terminal does show the same error.

```
$ xdg-open https://hiberglobal.atlassian.net/browse/WEB-4314
$ [261390:261390:1117/141915.417745:ERROR:chrome_content_client.cc(343)] Failed to locate and load the component updated flash plugin.
Opening in existing browser session.
echo $?
0
```

It is questionable that the Chromium stuff things it is an error that I don't have any flash plugins installed,... 🤷‍♂️

**Comment by danshumaker** [comment]
Thank you @mhogerheijde for submitting this. It's an interesting issue that I'm not sure we can get around but we'll try.  The open command is just a fancy process launcher.  We should be able to trap the return code of the exited process and act accordingly if it fails (ie. trap the exception and clean up the IO).

**Comment by mhogerheijde** [comment]
Also note that the browser opens and I get to see the page, so in functionality it does what it is supposed to do 👌
