### ISSUE TITLE
jira ls failing with error related to async package

### ISSUE THREAD

**Issue by criess** [danshumaker/jira-cli#45]
After I connected the cli sucessfully via config command I ran into an issue when trying to query with `ls` command. see output below:

```
$ jira ls -v
https://[…redacted…].atlassian.net/rest/api/2/search?jql=assignee=currentUser()+AND+status+in+("Open", "In Progress", "Reopened", "To Do", "In Review")+order+by+key+DESC&maxResults=500&startAt=0&maxResults=500
/usr/lib/node_modules/jira-cli/node_modules/async/dist/async.js:966
        if (fn === null) throw new Error("Callback was already called.");
                         ^

Error: Callback was already called.
    at /usr/lib/node_modules/jira-cli/node_modules/async/dist/async.js:966:32
    at next (/usr/lib/node_modules/jira-cli/node_modules/async/dist/async.js:3022:18)
    at /usr/lib/node_modules/jira-cli/lib/jira/ls.js:47:18
    at Request.callback (/usr/lib/node_modules/jira-cli/node_modules/superagent/lib/node/index.js:704:3)
    at /usr/lib/node_modules/jira-cli/node_modules/superagent/lib/node/index.js:891:18
    at Stream.<anonymous> (/usr/lib/node_modules/jira-cli/node_modules/superagent/lib/node/parsers/json.js:17:7)
    at Stream.emit (events.js:315:20)
    at Unzip.<anonymous> (/usr/lib/node_modules/jira-cli/node_modules/superagent/lib/node/unzip.js:54:12)
    at Unzip.emit (events.js:315:20)
    at endReadableNT (internal/streams/readable.js:1327:12)
```

It may have to do with dependendant libraries and their management (uneducated guess from me). I'll attach versions for the core components, ask me if you need more:

```
node --version;
npm --version;
jira -V;
v14.15.3
6.14.9
2.4.0
```

**Comment by danshumaker** [comment]
Quick question @criess .  Look inside your config file and see if all the ticket status's that you have in your instance of Jira match those within the config file.  The ticket status's that are in there are defaults.  Many installations of jira have customized workflows that rename their status'.  So when jira-cli gets their status' in order to list them and tries to map them to values in the config file-- if they don't map then an error (non-indicative or helpful) occurs.

This may or may not help but I have had it be the issue for at least two instances of Jira that I've used.   One of these days, I'd like to make setting these status's a part of the original configuration setup.. But for now we have to adjust them manually.

Hopefully this helps you .  If not, let me know and we'll debug it further.
